### ISSUE TITLE
Requires AWS_REGION env variable to be set

### ISSUE THREAD

**Issue by birme** [Eyevinn/iaf-plugin-aws#17]
The plugin requires that the AWS_REGION environment variable is set, even though region is specified in the constructor.

**Comment by oscnord** [comment]
@birme I've just tested this locally and I can seem to be able to reproduce this issue.

**Comment by oscnord** [comment]
tested both with the  `iaf-plugin-aws` and `iaf-plugin-aws-mediapackage` plugins.
